-- Generated by nwg-displays on 2026-05-19 at 12:47:39. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "8767x731",
    scale = 2.0
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@59.95",
    position = "6207x0",
    scale = 1.0
})
