-- Generated by nwg-displays on 2026-06-16 at 08:22:05. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "13247x481",
    scale = 2.0
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "10687x0",
    scale = 1.0
})
